version: '3'

services: 
  server-a:
    image: nginx:latest
    container_name: 'server-a'
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/:/etc/nginx/conf.d
      - ./contents/:/usr/share/nginx/
    networks: 
      - proxy-network
      - server-a-network

networks: 
  proxy-network:
    name: proxy-network
  server-a-network:
    name: server-a-network