version: '3'

services: 
  reverse-proxy:
    image: nginx:latest
    container_name: 'reverse-proxy'
    volumes: 
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d/:/etc/nginx/conf.d
    networks: 
      - proxy-network
    ports: 
      - 80:80


networks: 
  proxy-network:
    name: proxy-network